[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk

# build_src_flags can stay as they are for your original project
build_src_flags = 
    -O3 

# NOTE: 'board_build.pio' is NOT needed here anymore.
# 'CMakeLists.txt' is handling it.

debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200