[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk

# For regular work
# build_src_flags = -O0
# For release builds with optimizations
build_flags = 
    -O3
    -D PICO_CMSIS_DSP_INSTRUCTIONS=1
    -I include/drivers 
    -I include/systems
    -I include/third_party

board_build.pio = src/drivers/ili9486_8080.pio

# Add any required libraries here
# lib_deps =

debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200