[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk

# For regular work
# build_src_flags = -O0
# For release builds with optimizations
build_src_flags = 
    -O3
    -D PICO_CMSIS_DSP_INSTRUCTIONS=1
    -I include
    -I include/drivers
    -I include/systems
    -I lib/CMSIS-DSP/Include
    -I src/

board_build.pio = src/drivers/ili9486_8080.pio

# Add any required libraries here
lib_ldf_mode = chain+ # Helps PlatformIO resolve dependencies correctly
# lib_deps =

# Ensure all source files in src/ AND src/imported/ are compiled
lib_compat_mode = off
build_src_filter =
    +<*> # Includes src/* by default
    +<lib/*> # Explicitly include imported source files
    +<drivers/*> # Explicitly include driver files

debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200