/*******************************************************************************
 * @file        sd_card.c
 * @brief       Implements the functionality for the SD Card module.
 * @details     Complete set of functions to use the SD Card with SDIO.
 * 
 * @author      LED Chasers
 * @date        2025-10-14
 * 
 * @note        This module is designed to be used only during initialization
 *              to pull all the data into buffers.
 * 
 * @copyright   Copyright (c) 2025, LED Chasers. All rights reserved.
 ******************************************************************************/

/* ----------------------------- Private Includes --------------------------- */
#include "sd_card.h"
#include "config.h"
#include "structs.h"
#include "globals.h" // Uses g_sd_state

#include <stdio.h>
#include <string.h>
#include <assert.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/clocks.h"
#include "hardware/gpio.h"
#include "sd_card_sdio.pio.h" // Generated by pioasm
// ...

/* ---------------------------- Private Constants --------------------------- */

// --- SD Card Command Opcodes ---
#define CMD0_GO_IDLE_STATE              0
#define CMD2_ALL_SEND_CID               2
#define CMD3_SEND_RELATIVE_ADDR         3
#define CMD7_SELECT_CARD                7
#define CMD8_SEND_IF_COND               8
#define CMD9_SEND_CSD                   9
#define CMD12_STOP_TRANSMISSION         12
#define CMD13_SEND_STATUS               13
#define CMD17_READ_SINGLE_BLOCK         17
#define CMD18_READ_MULTIPLE_BLOCK       18
#define CMD55_APP_CMD                   55
#define ACMD6_SET_BUS_WIDTH             6
#define ACMD13_SD_STATUS                13
#define ACMD41_SD_SEND_OP_COND          41
#define ACMD42_SET_CLR_CARD_DETECT      42
// ...

/* ----------------------------- Private Variables -------------------------- */

static sd_driver_state_t g_sd_state; //Internal state of SD Card driver

// --- CRC7 Table ---
static const uint8_t crc7_table[256] = {
    0x00, 0x12, 0x24, 0x36, 0x48, 0x5a, 0x6c, 0x7e, 0x90, 0x82, 0xb4, 0xa6, 0xd8, 0xca, 0xfc, 0xee,
    0x32, 0x20, 0x16, 0x04, 0x7a, 0x68, 0x5e, 0x4c, 0xa2, 0xb0, 0x86, 0x94, 0xea, 0xf8, 0xce, 0xdc,
    0x64, 0x76, 0x40, 0x52, 0x2c, 0x3e, 0x08, 0x1a, 0xf4, 0xe6, 0xd0, 0xc2, 0xbc, 0xae, 0x98, 0x8a,
    0x56, 0x44, 0x72, 0x60, 0x1e, 0x0c, 0x3a, 0x28, 0xc6, 0xd4, 0xe2, 0xf0, 0x8e, 0x9c, 0xaa, 0xb8,
    0xc8, 0xda, 0xec, 0xfe, 0x80, 0x92, 0xa4, 0xb6, 0x58, 0x4a, 0x7c, 0x6e, 0x10, 0x02, 0x34, 0x26,
    0xfa, 0xe8, 0xde, 0xcc, 0xb2, 0xa0, 0x96, 0x84, 0x6a, 0x78, 0x4e, 0x5c, 0x22, 0x30, 0x06, 0x14,
    0xac, 0xbe, 0x88, 0x9a, 0xe4, 0xf6, 0xc0, 0xd2, 0x3c, 0x2e, 0x18, 0x0a, 0x74, 0x66, 0x50, 0x42,
    0x9e, 0x8c, 0xba, 0xa8, 0xd6, 0xc4, 0xf2, 0xe0, 0x0e, 0x1c, 0x2a, 0x38, 0x46, 0x54, 0x62, 0x70,
    0x82, 0x90, 0xa6, 0xb4, 0xca, 0xd8, 0xee, 0xfc, 0x12, 0x00, 0x36, 0x24, 0x5a, 0x48, 0x7e, 0x6c,
    0xb0, 0xa2, 0x94, 0x86, 0xf8, 0xea, 0xdc, 0xce, 0x20, 0x32, 0x04, 0x16, 0x68, 0x7a, 0x4c, 0x5e,
    0xe6, 0xf4, 0xc2, 0xd0, 0xae, 0xbc, 0x8a, 0x98, 0x76, 0x64, 0x52, 0x40, 0x3e, 0x2c, 0x1a, 0x08,
    0xd4, 0xc6, 0xf0, 0xe2, 0x9c, 0x8e, 0xb8, 0xaa, 0x44, 0x56, 0x60, 0x72, 0x0c, 0x1e, 0x28, 0x3a,
    0x4a, 0x58, 0x6e, 0x7c, 0x02, 0x10, 0x26, 0x34, 0xda, 0xc8, 0xfe, 0xec, 0x92, 0x80, 0xb6, 0xa4,
    0x78, 0x6a, 0x5c, 0x4e, 0x30, 0x22, 0x14, 0x06, 0xe8, 0xfa, 0xcc, 0xde, 0xa0, 0xb2, 0x84, 0x96,
    0x2e, 0x3c, 0x0a, 0x18, 0x66, 0x74, 0x42, 0x50, 0xbe, 0xac, 0x9a, 0x88, 0xf6, 0xe4, 0xd2, 0xc0,
    0x1c, 0x0e, 0x38, 0x2a, 0x54, 0x46, 0x70, 0x62, 0x8c, 0x9e, 0xa8, 0xba, 0xc4, 0xd6, 0xe0, 0xf2
};
// ...

/* ----------------------------- Private Functions -------------------------- */

// --- CRC16 ---
__attribute__((optimize("Ofast")))
static uint64_t sdio_crc16_4bit_checksum(uint32_t *data, uint32_t num_words) {
    uint64_t crc = 0;
    uint32_t *end = data + num_words;
    while (data < end) {
        for (int unroll = 0; unroll < 4; unroll++) {
            uint32_t data_in = __builtin_bswap32(*data++);
            uint32_t data_out = crc >> 32;
            crc <<= 32;
            data_out ^= (data_out >> 16);
            data_out ^= (data_in >> 16);
            uint64_t xorred = data_out ^ data_in;
            crc ^= xorred;
            crc ^= xorred << (5 * 4);
            crc ^= xorred << (12 * 4);
        }
    }
    return crc;
}

static void sdio_send_command(uint8_t command, uint32_t arg, uint8_t response_bits) {
    // Note: This function implicitly uses g_sd_state members
    // e.g., pio_sm_clear_fifos(SDIO_PIO, g_sd_state.cmd_sm);
    uint32_t word0 = (47 << 24) | (1 << 22) | (command << 16) | (((arg >> 24) & 0xFF) << 8) | (((arg >> 16) & 0xFF) << 0);
    uint32_t word1 = (((arg >> 8) & 0xFF) << 24) | (((arg >> 0) & 0xFF) << 16) | (1 << 8);
    if (response_bits) { word1 |= ((response_bits - 1) << 0); }
    uint8_t crc = 0;
    crc = crc7_table[crc ^ ((word0 >> 16) & 0xFF)];
    crc = crc7_table[crc ^ ((word0 >> 8) & 0xFF)];
    crc = crc7_table[crc ^ ((word0 >> 0) & 0xFF)];
    crc = crc7_table[crc ^ ((word1 >> 24) & 0xFF)];
    crc = crc7_table[crc ^ ((word1 >> 16) & 0xFF)];
    word1 |= crc << 8;
    pio_sm_clear_fifos(SDIO_PIO, g_sd_state.cmd_sm);
    pio_sm_put(SDIO_PIO, g_sd_state.cmd_sm, word0);
    pio_sm_put(SDIO_PIO, g_sd_state.cmd_sm, word1);
}

static sdio_status_t rp2040_sdio_command_R1(uint8_t command, uint32_t arg, uint32_t *response) {
    sdio_send_command(command, arg, response ? 48 : 0);
    uint32_t start = to_ms_since_boot(get_absolute_time());
    uint32_t wait_words = response ? 2 : 1;
    while (pio_sm_get_rx_fifo_level(SDIO_PIO, g_sd_state.cmd_sm) < wait_words) {
        if ((uint32_t)(to_ms_since_boot(get_absolute_time()) - start) > SD_CMD_TIMEOUT_MS) {
            pio_sm_clear_fifos(SDIO_PIO, g_sd_state.cmd_sm);
            pio_sm_exec(SDIO_PIO, g_sd_state.cmd_sm, pio_encode_jmp(g_sd_state.pio_cmd_clk_offset));
            return g_sd_state.last_error = SDIO_ERR_RESPONSE_TIMEOUT;
        }
    }
    if (response) {
        uint32_t resp0 = pio_sm_get(SDIO_PIO, g_sd_state.cmd_sm);
        uint32_t resp1 = pio_sm_get(SDIO_PIO, g_sd_state.cmd_sm);
        uint8_t crc = 0;
        crc = crc7_table[crc ^ ((resp0 >> 24) & 0xFF)];
        crc = crc7_table[crc ^ ((resp0 >> 16) & 0xFF)];
        crc = crc7_table[crc ^ ((resp0 >> 8) & 0xFF)];
        crc = crc7_table[crc ^ ((resp0 >> 0) & 0xFF)];
        crc = crc7_table[crc ^ ((resp1 >> 8) & 0xFF)];
        uint8_t actual_crc = ((resp1 >> 0) & 0xFE);
        if (crc != actual_crc) return g_sd_state.last_error = SDIO_ERR_RESPONSE_CRC;
        uint8_t response_cmd = ((resp0 >> 24) & 0xFF);
        if (response_cmd != command && command != 41) return g_sd_state.last_error = SDIO_ERR_RESPONSE_CODE;
        *response = ((resp0 & 0xFFFFFF) << 8) | ((resp1 >> 8) & 0xFF);
    } else {
        pio_sm_get(SDIO_PIO, g_sd_state.cmd_sm);
    }
    return g_sd_state.last_error = SDIO_OK;
}

static sdio_status_t rp2040_sdio_command_R2(uint8_t command, uint32_t arg, uint8_t *response) {
    pio_sm_clear_fifos(SDIO_PIO, g_sd_state.cmd_sm);
    uint32_t response_buf[5];
    dma_channel_config dmacfg = dma_channel_get_default_config(g_sd_state.dma_ch_a);
    channel_config_set_transfer_data_size(&dmacfg, DMA_SIZE_32);
    channel_config_set_read_increment(&dmacfg, false);
    channel_config_set_write_increment(&dmacfg, true);
    channel_config_set_dreq(&dmacfg, pio_get_dreq(SDIO_PIO, g_sd_state.cmd_sm, false));
    dma_channel_configure(g_sd_state.dma_ch_a, &dmacfg, &response_buf, &SDIO_PIO->rxf[g_sd_state.cmd_sm], 5, true);
    sdio_send_command(command, arg, 136);
    uint32_t start = to_ms_since_boot(get_absolute_time());
    while (dma_channel_is_busy(g_sd_state.dma_ch_a)) {
        if ((uint32_t)(to_ms_since_boot(get_absolute_time()) - start) > SD_CMD_TIMEOUT_MS) {
            dma_channel_abort(g_sd_state.dma_ch_a);
            pio_sm_clear_fifos(SDIO_PIO, g_sd_state.cmd_sm);
            pio_sm_exec(SDIO_PIO, g_sd_state.cmd_sm, pio_encode_jmp(g_sd_state.pio_cmd_clk_offset));
            return g_sd_state.last_error = SDIO_ERR_RESPONSE_TIMEOUT;
        }
    }
    response[0] = ((response_buf[0] >> 16) & 0xFF);
    response[1] = ((response_buf[0] >> 8) & 0xFF);
    response[2] = ((response_buf[0] >> 0) & 0xFF);
    response[3] = ((response_buf[1] >> 24) & 0xFF);
    response[4] = ((response_buf[1] >> 16) & 0xFF);
    response[5] = ((response_buf[1] >> 8) & 0xFF);
    response[6] = ((response_buf[1] >> 0) & 0xFF);
    response[7] = ((response_buf[2] >> 24) & 0xFF);
    response[8] = ((response_buf[2] >> 16) & 0xFF);
    response[9] = ((response_buf[2] >> 8) & 0xFF);
    response[10] = ((response_buf[2] >> 0) & 0xFF);
    response[11] = ((response_buf[3] >> 24) & 0xFF);
    response[12] = ((response_buf[3] >> 16) & 0xFF);
    response[13] = ((response_buf[3] >> 8) & 0xFF);
    response[14] = ((response_buf[3] >> 0) & 0xFF);
    response[15] = ((response_buf[4] >> 0) & 0xFF);
    return g_sd_state.last_error = SDIO_OK;
}

static sdio_status_t rp2040_sdio_command_R3(uint8_t command, uint32_t arg, uint32_t *response) {
    sdio_send_command(command, arg, 48);
    uint32_t start = to_ms_since_boot(get_absolute_time());
    while (pio_sm_get_rx_fifo_level(SDIO_PIO, g_sd_state.cmd_sm) < 2) {
        if ((uint32_t)(to_ms_since_boot(get_absolute_time()) - start) > SD_CMD_TIMEOUT_MS) {
            pio_sm_clear_fifos(SDIO_PIO, g_sd_state.cmd_sm);
            pio_sm_exec(SDIO_PIO, g_sd_state.cmd_sm, pio_encode_jmp(g_sd_state.pio_cmd_clk_offset));
            return g_sd_state.last_error = SDIO_ERR_RESPONSE_TIMEOUT;
        }
    }
    uint32_t resp0 = pio_sm_get(SDIO_PIO, g_sd_state.cmd_sm);
    uint32_t resp1 = pio_sm_get(SDIO_PIO, g_sd_state.cmd_sm);
    *response = ((resp0 & 0xFFFFFF) << 8) | ((resp1 >> 8) & 0xFF);
    return g_sd_state.last_error = SDIO_OK;
}

static sdio_status_t rp2040_sdio_stop() {
    dma_channel_abort(g_sd_state.dma_ch_a);
    dma_channel_abort(g_sd_state.dma_ch_b);
    pio_sm_set_enabled(SDIO_PIO, g_sd_state.data_sm, false);
    pio_sm_set_consecutive_pindirs(SDIO_PIO, g_sd_state.data_sm, g_sd_state.d0_gpio, 4, false);
    return SDIO_OK;
}

static sdio_status_t rp2040_sdio_rx_start(uint8_t *buffer, uint32_t num_blocks) {
    assert(((uint32_t)buffer & 3) == 0 && num_blocks <= SDIO_MAX_BLOCKS);
    g_sd_state.transfer_start_time = to_ms_since_boot(get_absolute_time());
    g_sd_state.data_buf = (uint32_t*)buffer;
    g_sd_state.blocks_done = 0;
    g_sd_state.total_blocks = num_blocks;
    g_sd_state.blocks_checksumed = 0;
    g_sd_state.checksum_errors = 0;
    for (uint32_t i = 0; i < num_blocks; i++) {
        g_sd_state.dma_blocks[i * 2].write_addr = buffer + i * SD_BLOCK_SIZE;
        g_sd_state.dma_blocks[i * 2].transfer_count = SD_BLOCK_SIZE / sizeof(uint32_t);
        g_sd_state.dma_blocks[i * 2 + 1].write_addr = &g_sd_state.received_checksums[i];
        g_sd_state.dma_blocks[i * 2 + 1].transfer_count = 2;
    }
    g_sd_state.dma_blocks[num_blocks * 2].write_addr = 0;
    g_sd_state.dma_blocks[num_blocks * 2].transfer_count = 0;
    dma_channel_config dmacfg = dma_channel_get_default_config(g_sd_state.dma_ch_a);
    channel_config_set_transfer_data_size(&dmacfg, DMA_SIZE_32);
    channel_config_set_read_increment(&dmacfg, false);
    channel_config_set_write_increment(&dmacfg, true);
    channel_config_set_dreq(&dmacfg, pio_get_dreq(SDIO_PIO, g_sd_state.data_sm, false));
    channel_config_set_bswap(&dmacfg, true);
    channel_config_set_chain_to(&dmacfg, g_sd_state.dma_ch_b);
    dma_channel_configure(g_sd_state.dma_ch_a, &dmacfg, 0, &SDIO_PIO->rxf[g_sd_state.data_sm], 0, false);
    dmacfg = dma_channel_get_default_config(g_sd_state.dma_ch_b);
    channel_config_set_transfer_data_size(&dmacfg, DMA_SIZE_32);
    channel_config_set_read_increment(&dmacfg, true);
    channel_config_set_write_increment(&dmacfg, true);
    channel_config_set_ring(&dmacfg, true, 3);
    dma_channel_configure(g_sd_state.dma_ch_b, &dmacfg, &dma_hw->ch[g_sd_state.dma_ch_a].al1_write_addr, g_sd_state.dma_blocks, 2, false);
    pio_sm_init(SDIO_PIO, g_sd_state.data_sm, g_sd_state.pio_data_rx_offset, &g_sd_state.pio_cfg_data_rx);
    pio_sm_set_consecutive_pindirs(SDIO_PIO, g_sd_state.data_sm, g_sd_state.d0_gpio, 4, false);
    pio_sm_put(SDIO_PIO, g_sd_state.data_sm, (SD_BLOCK_SIZE + 8) * 2 - 1);
    pio_sm_exec(SDIO_PIO, g_sd_state.data_sm, pio_encode_out(pio_y, 32));
    SDIO_PIO->sm[g_sd_state.data_sm].shiftctrl |= PIO_SM0_SHIFTCTRL_FJOIN_RX_BITS;
    dma_channel_start(g_sd_state.dma_ch_b);
    pio_sm_set_enabled(SDIO_PIO, g_sd_state.data_sm, true);
    return g_sd_state.last_error = SDIO_OK;
}

static void sdio_verify_rx_checksums(uint32_t maxcount) {
    while (g_sd_state.blocks_checksumed < g_sd_state.blocks_done && maxcount-- > 0) {
        int blockidx = g_sd_state.blocks_checksumed++;
        uint64_t checksum = sdio_crc16_4bit_checksum(g_sd_state.data_buf + blockidx * (SD_BLOCK_SIZE / 4), (SD_BLOCK_SIZE / 4));
        uint32_t top = __builtin_bswap32(g_sd_state.received_checksums[blockidx].top);
        uint32_t bottom = __builtin_bswap32(g_sd_state.received_checksums[blockidx].bottom);
        uint64_t expected = ((uint64_t)top << 32) | bottom;
        if (checksum != expected) {
            g_sd_state.checksum_errors++;
        }
    }
}

static sdio_status_t rp2040_sdio_rx_poll() {
    bool done = false;
    if (g_sd_state.blocks_done >= g_sd_state.total_blocks) {
        done = true;
    } else {
        sdio_verify_rx_checksums(4);
        uint32_t dma_ctrl_block_count = (dma_hw->ch[g_sd_state.dma_ch_b].read_addr - (uint32_t)&g_sd_state.dma_blocks);
        dma_ctrl_block_count /= sizeof(g_sd_state.dma_blocks[0]);
        g_sd_state.blocks_done = (dma_ctrl_block_count - 1) / 2;
        if (g_sd_state.blocks_done >= g_sd_state.total_blocks) {
            done = true;
        }
    }
    if (done) {
        sdio_verify_rx_checksums(g_sd_state.total_blocks);
        rp2040_sdio_stop();
        if (g_sd_state.checksum_errors > 0) {
            printf("SDIO: %lu checksum errors!\n", g_sd_state.checksum_errors);
            return g_sd_state.last_error = SDIO_ERR_DATA_CRC;
        }
        return g_sd_state.last_error = SDIO_OK;
    }
    if (to_ms_since_boot(get_absolute_time()) - g_sd_state.transfer_start_time >= SD_READ_TIMEOUT_MS) {
        printf("SDIO: Read poll timeout\n");
        rp2040_sdio_stop();
        return g_sd_state.last_error = SDIO_ERR_DATA_TIMEOUT;
    }
    return g_sd_state.last_error = SDIO_BUSY;
}

static bool sd_sdio_stop_transmission() {
    uint32_t reply;
    if (rp2040_sdio_command_R1(CMD12_STOP_TRANSMISSION, 0, &reply) != SDIO_OK) {
        return false;
    }
    uint32_t start = to_ms_since_boot(get_absolute_time());
    while ((sio_hw->gpio_in & (1 << g_sd_state.d0_gpio)) == 0) {
        if (to_ms_since_boot(get_absolute_time()) - start > SD_CMD_TIMEOUT_MS) {
            printf("SDIO: Stop transmission timeout\n");
            return false;
        }
    }
    return true;
}

static float calculate_clk_div(uint baud) {
    float div = (float)clock_get_hz(clk_sys) / (CLKDIV * baud);
    if (div < 1.0) div = 1.0;
    if (div > 65536.0) div = 65536.0;
    return div;
}

static bool rp2040_sdio_hw_init(float clk_div) {
    static bool resources_claimed = false;
    if (!resources_claimed) {
        g_sd_state.cmd_sm = pio_claim_unused_sm(SDIO_PIO, true);
        g_sd_state.data_sm = pio_claim_unused_sm(SDIO_PIO, true);
        g_sd_state.dma_ch_a = dma_claim_unused_channel(true);
        g_sd_state.dma_ch_b = dma_claim_unused_channel(true);
        resources_claimed = true;
    }
    dma_channel_abort(g_sd_state.dma_ch_a);
    dma_channel_abort(g_sd_state.dma_ch_b);
    pio_sm_set_enabled(SDIO_PIO, g_sd_state.cmd_sm, false);
    pio_sm_set_enabled(SDIO_PIO, g_sd_state.data_sm, false);
    pio_clear_instruction_memory(SDIO_PIO);

    g_sd_state.pio_cmd_clk_offset = pio_add_program(SDIO_PIO, &sdio_cmd_clk_program);
    pio_sm_config cfg = sdio_cmd_clk_program_get_default_config(g_sd_state.pio_cmd_clk_offset);
    sm_config_set_out_pins(&cfg, g_sd_state.cmd_gpio, 1);
    sm_config_set_in_pins(&cfg, g_sd_state.cmd_gpio);
    sm_config_set_set_pins(&cfg, g_sd_state.cmd_gpio, 1);
    sm_config_set_jmp_pin(&cfg, g_sd_state.cmd_gpio);
    sm_config_set_sideset_pins(&cfg, g_sd_state.clk_gpio);
    sm_config_set_out_shift(&cfg, false, true, 32);
    sm_config_set_in_shift(&cfg, false, true, 32);
    sm_config_set_clkdiv(&cfg, clk_div);
    sm_config_set_mov_status(&cfg, STATUS_TX_LESSTHAN, 2);
    pio_sm_init(SDIO_PIO, g_sd_state.cmd_sm, g_sd_state.pio_cmd_clk_offset, &cfg);
    pio_sm_set_consecutive_pindirs(SDIO_PIO, g_sd_state.cmd_sm, g_sd_state.clk_gpio, 1, true);
    pio_sm_set_enabled(SDIO_PIO, g_sd_state.cmd_sm, true);

    g_sd_state.pio_data_rx_offset = pio_add_program(SDIO_PIO, &sdio_data_rx_program);
    g_sd_state.pio_cfg_data_rx = sdio_data_rx_program_get_default_config(g_sd_state.pio_data_rx_offset);
    sm_config_set_in_pins(&g_sd_state.pio_cfg_data_rx, g_sd_state.d0_gpio);
    sm_config_set_in_shift(&g_sd_state.pio_cfg_data_rx, false, true, 32);
    sm_config_set_out_shift(&g_sd_state.pio_cfg_data_rx, false, true, 32);
    sm_config_set_clkdiv(&g_sd_state.pio_cfg_data_rx, clk_div);

    uint32_t pin_mask = (1 << (g_sd_state.clk_gpio - 30)) | (1 << (g_sd_state.cmd_gpio - 30)) | (1 << (g_sd_state.d0_gpio - 30)) | (1 << (g_sd_state.d1_gpio - 30)) | (1 << (g_sd_state.d2_gpio - 30)) | (1 << (g_sd_state.d3_gpio - 30));
    SDIO_PIO->input_sync_bypass |= pin_mask;

    gpio_set_function(g_sd_state.cmd_gpio, SDIO_GPIO_FUNC);
    gpio_set_function(g_sd_state.clk_gpio, SDIO_GPIO_FUNC);
    gpio_set_function(g_sd_state.d0_gpio, SDIO_GPIO_FUNC);
    gpio_set_function(g_sd_state.d1_gpio, SDIO_GPIO_FUNC);
    gpio_set_function(g_sd_state.d2_gpio, SDIO_GPIO_FUNC);
    gpio_set_function(g_sd_state.d3_gpio, SDIO_GPIO_FUNC);
    
    gpio_set_slew_rate(g_sd_state.cmd_gpio, GPIO_SLEW_RATE_FAST);
    gpio_set_slew_rate(g_sd_state.clk_gpio, GPIO_SLEW_RATE_FAST);
    gpio_set_slew_rate(g_sd_state.d0_gpio, GPIO_SLEW_RATE_FAST);
    gpio_set_slew_rate(g_sd_state.d1_gpio, GPIO_SLEW_RATE_FAST);
    gpio_set_slew_rate(g_sd_state.d2_gpio, GPIO_SLEW_RATE_FAST);
    gpio_set_slew_rate(g_sd_state.d3_gpio, GPIO_SLEW_RATE_FAST);
    
    gpio_set_drive_strength(g_sd_state.cmd_gpio, GPIO_DRIVE_STRENGTH_8MA);
    gpio_set_drive_strength(g_sd_state.clk_gpio, GPIO_DRIVE_STRENGTH_8MA);
    gpio_set_drive_strength(g_sd_state.d0_gpio, GPIO_DRIVE_STRENGTH_8MA);
    gpio_set_drive_strength(g_sd_state.d1_gpio, GPIO_DRIVE_STRENGTH_8MA);
    gpio_set_drive_strength(g_sd_state.d2_gpio, GPIO_DRIVE_STRENGTH_8MA);
    gpio_set_drive_strength(g_sd_state.d3_gpio, GPIO_DRIVE_STRENGTH_8MA);
    
    return true;
}
// ...

/* ----------------------------- Public Functions --------------------------- */

int sd_init(void) {
    memset(&g_sd_state, 0, sizeof(g_sd_state));
    
    // Store pin configuration from config.h
    g_sd_state.clk_gpio = PIN_SDIO_CLK;
    g_sd_state.cmd_gpio = PIN_SDIO_CMD;
    g_sd_state.d0_gpio = PIN_SDIO_D0;
    g_sd_state.d1_gpio = PIN_SDIO_D0 + 1;
    g_sd_state.d2_gpio = PIN_SDIO_D0 + 2;
    g_sd_state.d3_gpio = PIN_SDIO_D0 + 3;

    if (PIN_SDIO_CLK < 30 || PIN_SDIO_CMD < 30 || PIN_SDIO_D0 < 30) {
        printf("SDIO: All pins must be in the high bank (GPIO >= 30)\n");
        return -1;
    }

    uint32_t reply;
    sdio_status_t status;
    if (!rp2040_sdio_hw_init(calculate_clk_div(SD_INIT_BAUD_RATE))) return -2;
    rp2040_sdio_command_R1(CMD0_GO_IDLE_STATE, 0, NULL);
    status = rp2040_sdio_command_R1(CMD8_SEND_IF_COND, 0x1AA, &reply);
    if (status != SDIO_OK || reply != 0x1AA) {
        printf("SDIO: Card failed CMD8. Not an SDHC card?\n");
        return -3;
    }
    uint32_t start = to_ms_since_boot(get_absolute_time());
    do {
        if (rp2040_sdio_command_R1(CMD55_APP_CMD, 0, &reply) != SDIO_OK ||
            rp2040_sdio_command_R3(ACMD41_SD_SEND_OP_COND, 0xC0100000, &g_sd_state.ocr) != SDIO_OK) {
            printf("SDIO: Failed ACMD41 sequence.\n");
            return -4;
        }
        if ((uint32_t)(to_ms_since_boot(get_absolute_time()) - start) > 1000) {
            printf("SDIO: Init timeout (ACMD41)\n");
            return -5;
        }
    } while (!(g_sd_state.ocr & (1 << 31)));
    uint8_t cid_buffer[16];
    if (rp2040_sdio_command_R2(CMD2_ALL_SEND_CID, 0, cid_buffer) != SDIO_OK) return -6;
    if (rp2040_sdio_command_R1(CMD3_SEND_RELATIVE_ADDR, 0, &g_sd_state.rca) != SDIO_OK) return -7;
    uint8_t csd_buffer[16];
    if (rp2040_sdio_command_R2(CMD9_SEND_CSD, g_sd_state.rca, csd_buffer) != SDIO_OK) return -8;
    if (rp2040_sdio_command_R1(CMD7_SELECT_CARD, g_sd_state.rca, &reply) != SDIO_OK) return -9;
    if (rp2040_sdio_command_R1(CMD55_APP_CMD, g_sd_state.rca, &reply) != SDIO_OK ||
        rp2040_sdio_command_R1(ACMD42_SET_CLR_CARD_DETECT, 0, &reply) != SDIO_OK) return -10;
    if (rp2040_sdio_command_R1(CMD55_APP_CMD, g_sd_state.rca, &reply) != SDIO_OK ||
        rp2040_sdio_command_R1(ACMD6_SET_BUS_WIDTH, 2, &reply) != SDIO_OK) return -11;
    if (!rp2040_sdio_hw_init(calculate_clk_div(SD_BAUD_RATE))) return -12;

    printf("SDIO: Card initialized successfully.\n");
    return 0;
}

int sd_read_blocks(uint32_t sector, uint8_t *buffer, uint32_t num_sectors) {
    // (Function content unchanged)
    if (num_sectors == 0) return 0;
    if (num_sectors > SDIO_MAX_BLOCKS) {
         printf("SDIO: Read request exceeds max blocks (%d)\n", SDIO_MAX_BLOCKS);
        return -1;
    }
    if (((uint32_t)buffer & 3) != 0) {
        printf("SDIO: Read buffer must be 32-bit aligned.\n");
        return -2;
    }
    uint32_t reply;
    uint32_t cmd = (num_sectors > 1) ? CMD18_READ_MULTIPLE_BLOCK : CMD17_READ_SINGLE_BLOCK;
    if (rp2040_sdio_rx_start(buffer, num_sectors) != SDIO_OK ||
        rp2040_sdio_command_R1(cmd, sector, &reply) != SDIO_OK) {
        printf("SDIO: Failed to start read command.\n");
        rp2040_sdio_stop();
        return -3;
    }
    sdio_status_t status;
    do {
        status = rp2040_sdio_rx_poll();
    } while (status == SDIO_BUSY);
    if (status != SDIO_OK) {
        printf("SDIO: Read poll failed.\n");
        sd_sdio_stop_transmission();
        return -4;
    }
    if (num_sectors > 1) {
        if (!sd_sdio_stop_transmission()) {
            printf("SDIO: Failed to stop multi-block read.\n");
            return -5;
        }
    }
    return 0;
}
