// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// led_chaser //
// ---------- //

#define led_chaser_wrap_target 0
#define led_chaser_wrap 2
#define led_chaser_pio_version 0

static const uint16_t led_chaser_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6004, //  1: out    pins, 4
    0xbf42, //  2: nop                           [31]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program led_chaser_program = {
    .instructions = led_chaser_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = led_chaser_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config led_chaser_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + led_chaser_wrap_target, offset + led_chaser_wrap);
    return c;
}
#endif

