// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#ifndef _PIO_LCD_PARALLEL_PIO_H
#define _PIO_LCD_PARALLEL_PIO_H

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// lcd_parallel     //
// ---------------- //

#define lcd_parallel_wrap_target 0
#define lcd_parallel_wrap 3

static const uint16_t lcd_parallel_program_instructions[] = {
            //     .wrap_target
    0x6010, //  0: out    pins, 17        
    0x606e, //  1: out    null, 15        
    0x1282, //  2: mov    y, y          side 0 [1] 
    0x1b83, //  3: mov    y, y          side 1 [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program lcd_parallel_program = {
    .instructions = lcd_parallel_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config lcd_parallel_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + lcd_parallel_wrap_target, offset + lcd_parallel_wrap);
    sm_config_set_sideset(&c, 1, true, false);
    return c;
}

// ------------------ //
// C-SDK helper block //
// ------------------ //

#include "pico/stdlib.h"
#include "hardware/pio.h"

static inline void lcd_parallel_program_init(
    PIO pio, uint sm, uint offset,
    uint pin_data_base,   // First data pin (DB0)
    uint pin_wr,          // WR strobe pin
    float clkdiv
) {
    pio_sm_config c = lcd_parallel_program_get_default_config(offset);

    sm_config_set_out_pins(&c, pin_data_base, 17);  // DB0..DB15 + DC
    sm_config_set_sideset_pins(&c, pin_wr);         // WR via side-set

    sm_config_set_out_shift(&c,
        false,   // shift right
        true,   // autopull
        32);    // pull threshold

    sm_config_set_clkdiv(&c, clkdiv);

    // Init pins
    for (uint i = 0; i < 17; i++)
        pio_gpio_init(pio, pin_data_base + i);
    pio_gpio_init(pio, pin_wr);

    // Set directions
    pio_sm_set_consecutive_pindirs(pio, sm, pin_data_base, 17, true);
    pio_sm_set_pindirs_with_mask(pio, sm, (1u << pin_wr), (1u << pin_wr));

    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif // !PICO_NO_HARDWARE

#endif // _PIO_LCD_PARALLEL_PIO_H