// -------------------------------------------------- //
// This file is autogenerated by pioasm
// Source: lcd_parallel.pio
// -------------------------------------------------- //

#ifndef LCD_PARALLEL_PIO_H
#define LCD_PARALLEL_PIO_H

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// lcd_parallel
// --- //

#define lcd_parallel_wrap_target 0
#define lcd_parallel_wrap 3

// This program is 4 instructions long.
static const uint16_t lcd_parallel_program_instructions[] = {
    //     .wrap_target
    0x7051, //  0: out    pins, 17       side 1 
    0x700f, //  1: out    null, 15       side 1 
    0x02ad, //  2: mov    y, y           side 0 [2] ; (nop)
    0x13ad, //  3: mov    y, y           side 1 [3] ; (nop)
    //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program lcd_parallel_program = {
    .instructions = lcd_parallel_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config lcd_parallel_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + lcd_parallel_wrap_target, offset + lcd_parallel_wrap);
    // Configures side-set for 1 pin, optional=true
    sm_config_set_sideset(&c, 1, true, false);
    return c;
}
#endif

// ---------------- //
// C-SDK Functions
// ---------------- //

#include "pico/stdlib.h"
#include "hardware/pio.h"

static inline void lcd_parallel_program_init(
    PIO pio, uint sm, uint offset,
    uint pin_data_base,   // First data pin (DB0)
    uint pin_wr,          // WR strobe pin
    float clkdiv
) {
    pio_sm_set_enabled(pio, sm, false);

    // Init pins
    for (uint i = 0; i < 17; i++)
        pio_gpio_init(pio, pin_data_base + i);
    pio_gpio_init(pio, pin_wr);

    // Set directions
    pio_sm_set_consecutive_pindirs(pio, sm, pin_data_base, 17, true);
    pio_sm_set_pindirs_with_mask(pio, sm, (1u << pin_wr), (1u << pin_wr));

    // Intialize WR
    pio_sm_set_pins_with_mask(pio, sm, 1u << pin_wr, 1u << pin_wr);

    pio_sm_config c = lcd_parallel_program_get_default_config(offset);

    // Set clock
    sm_config_set_clkdiv(&c, clkdiv);

    // Set output pins D0-D16
    sm_config_set_out_pin_base(&c, pin_data_base);
    sm_config_set_out_pin_count(&c, 17);
    sm_config_set_out_pins(&c, pin_data_base, 17);
    
    // Set Side-set (WR)
    sm_config_set_sideset_pins(&c, pin_wr);         // WR via side-set
    
    // This call is redundant as the default config already sets it,
    // but it correctly configures for 1 pin, optional=true.
    sm_config_set_sideset(&c, 1u, true, false);

    sm_config_set_out_shift(&c,
        true,   // shift right
        true,   // autopull
        32);    // pull threshold

    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif // LCD_PARALLEL_PIO_H