// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// 16-bit parallel                                    //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// lcd_parallel //
// ------ //

#define lcd_parallel_wrap_target 7
#define lcd_parallel_wrap 20
#define lcd_parallel_offset_block_fill 0u
#define lcd_parallel_offset_start_8 7u
#define lcd_parallel_offset_start_tx 7u
#define lcd_parallel_offset_set_addr_window 10u

static const uint16_t lcd_parallel_program_instructions[] = {
    0x98a0, //  0: pull   block           side 1     
    0xa027, //  1: mov    x, osr                     
    0x80a0, //  2: pull   block                      
    0xa047, //  3: mov    y, osr                     
    0xb8e1, //  4: mov    osr, x          side 1     
    0x7100, //  5: out    pins, 32        side 0 [1] 
    0x1884, //  6: jmp    y--, 4          side 1     
            //     .wrap_target
    0x98a0, //  7: pull   block           side 1     
    0x7100, //  8: out    pins, 32        side 0 [1] 
    0x1807, //  9: jmp    7               side 1     
    0xf822, // 10: set    x, 2            side 1     
    0xe000, // 11: set    pins, 0                    
    0x80a0, // 12: pull   block                      
    0x7000, // 13: out    pins, 32        side 0     
    0x0033, // 14: jmp    !x, 19                     
    0x98a0, // 15: pull   block           side 1     
    0xe001, // 16: set    pins, 1                    
    0x7108, // 17: out    pins, 8         side 0 [1] 
    0x19f1, // 18: jmp    !osre, 17       side 1 [1] 
    0x184b, // 19: jmp    x--, 11         side 1     
    0xe001, // 20: set    pins, 1                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program lcd_parallel_program = {
    .instructions = lcd_parallel_program_instructions,
    .length = 21,
    .origin = -1,
};

static inline pio_sm_config lcd_parallel_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + lcd_parallel_wrap_target, offset + lcd_parallel_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif


// // C-SDK block defined in the .pio file:
// #include "pico/stdlib.h"
// #include "hardware/pio.h"

// static inline void lcd_parallel_program_init(
//     PIO pio, uint sm, uint offset,
//     uint pin_data_base,   // First data pin (DB0)
//     uint pin_wr,          // WR strobe pin
//     float clkdiv
// ) {
//     pio_sm_set_enabled(pio, sm, false);

//     // Init pins
//     for (uint i = 0; i < 17; i++)
//         pio_gpio_init(pio, pin_data_base + i);
//     pio_gpio_init(pio, pin_wr);

//     // Set directions
//     pio_sm_set_consecutive_pindirs(pio, sm, pin_data_base, 17, true);
//     pio_sm_set_pindirs_with_mask(pio, sm, (1u << pin_wr), (1u << pin_wr));

//     // Intialize WR
//     pio_sm_set_pins_with_mask(pio, sm, 1u << pin_wr, 1u << pin_wr);

//     pio_sm_config c = lcd_parallel_program_get_default_config(offset);

//     // Set clock
//     sm_config_set_clkdiv(&c, clkdiv);

//     // Set output pins D0-D16
//     sm_config_set_out_pin_base(&c, pin_data_base);
//     sm_config_set_out_pin_count(&c, 17);
//     sm_config_set_out_pins(&c, pin_data_base, 17);
    
//     // Set Side-set (WR)
//     sm_config_set_sideset_pins(&c, pin_wr);         // WR via side-set
//     sm_config_set_sideset(&c, 1u, true, false);

//     sm_config_set_out_shift(&c,
//         true,   // shift right
//         true,   // autopull
//         0);     // pull threshold

//     pio_sm_init(pio, sm, offset, &c);
//     pio_sm_set_enabled(pio, sm, true);
// }
// // End of C-SDK block