// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// (Manually created to bypass PlatformIO build issue)//
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// sdio_cmd_clk //
// ---------------- //

#define sdio_cmd_clk_wrap_target 1
#define sdio_cmd_clk_wrap 18

#define sdio_cmd_clk_D0 1
#define sdio_cmd_clk_D1 1
#define CLKDIV 4

static const uint16_t sdio_cmd_clk_program_instructions[] = {
    0xa142, //  0: mov    osr, null        side 1 [1] 
//     .wrap_target
    0x614a, //  1: out    y, !status       side 0 [1] 
    0x0181, //  2: jmp    !y, 1            side 1 [1] 
    0x61e0, //  3: out    null, 32         side 0 [1] 
    0x6108, //  4: out    x, 8             side 1 [1] 
    0xe101, //  5: set    pins, 1          side 0 [1] 
    0xe121, //  6: set    pindirs, 1       side 1 [1] 
    0x6101, //  7: out    pins, 1          side 0 [1] 
    0x0147, //  8: jmp    x--, 7           side 1 [1] 
    0xe120, //  9: set    pindirs, 0       side 0 [1] 
    0x6108, // 10: out    x, 8             side 1 [1] 
    0x6100, // 11: out    pins, 0          side 0 [1] 
    0x01cf, // 12: jmp    !x, 15           side 1 [1] 
    0x6100, // 13: out    pins, 0          side 0 [1] 
    0x01cd, // 14: jmp    pin, 13          side 1 [1] 
    0x4101, // 15: in     pins, 1          side 0 [1] 
    0x014f, // 16: jmp    x--, 15          side 1 [1] 
    0x8120, // 17: push   iffull block     side 0 [1] 
//     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_cmd_clk_program = {
    .instructions = sdio_cmd_clk_program_instructions,
    .length = 18,
    .origin = -1,
};

static inline pio_sm_config sdio_cmd_clk_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_cmd_clk_wrap_target, offset + sdio_cmd_clk_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ------------- //
// sdio_data_rx //
// ------------- //

#define sdio_data_rx_wrap_target 3
#define sdio_data_rx_wrap 4

#define sdio_data_rx_D0 1
#define sdio_data_rx_D1 1
//#define CLKDIV 4 // Already defined above

static const uint16_t sdio_data_rx_program_instructions[] = {
    0xa027, //  0: mov    x, y             
    0x20a1, //  1: wait   0 gpio, 33       
    0x3fa1, //  2: wait   1 gpio, 31   [3] 
//     .wrap_target
    0x4004, //  3: in     pins, 4      [2] 
    0x0043, //  4: jmp    x--, 3           
//     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sdio_data_rx_program = {
    .instructions = sdio_data_rx_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config sdio_data_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sdio_data_rx_wrap_target, offset + sdio_data_rx_wrap);
    return c;
}
#endif